apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vllm-inference
  labels:
    app: granite-4.0-h-small-fp8
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
