apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qwen-32b-inference

resources:
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
