FROM registry.redhat.io/rhaiis/vllm-cuda-rhel9:3.3.3

USER 0

ENV MODEL_PATH=/models/Qwen3-4B \
    HF_HUB_OFFLINE=1 \
    TRANSFORMERS_OFFLINE=1 \
    HF_HUB_DISABLE_TELEMETRY=1 \
    VLLM_NO_USAGE_STATS=1

COPY --chown=0:0 --chmod=775 ./qwen-model ${MODEL_PATH}

USER 1001

EXPOSE 8000

ENTRYPOINT ["vllm", "serve"]
CMD ["/models/Qwen3-4B", "--host", "0.0.0.0", "--port", "8000"]
