apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gemma-3-12b-inference

resources:
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - deployment.yaml
  - service.yaml
