apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vllm-inference
  labels:
    app: gemma-3-12b-it
subjects:
  - kind: ServiceAccount
    name: vllm-inference
roleRef:
  kind: Role
  name: vllm-inference
  apiGroup: rbac.authorization.k8s.io
