apiVersion: v1
kind: Service
metadata:
  name: granite-guardian-3-2-5b
  labels:
    app: granite-guardian-3-2-5b
spec:
  selector:
    app: granite-guardian-3-2-5b
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  type: ClusterIP
