FROM registry.redhat.io/rhaii-preview/vllm-cuda-rhel9:1786522102

USER 0

ENV MODEL_PATH=/models/gpt-oss-120b \
    HF_HUB_OFFLINE=1 \
    TRANSFORMERS_OFFLINE=1

COPY --chown=0:0 --chmod=775 ./model ${MODEL_PATH}

USER 1001

EXPOSE 8000

ENTRYPOINT ["vllm", "serve"]
CMD ["/models/gpt-oss-120b", "--host", "0.0.0.0", "--port", "8000", "--quantization", "mxfp4", "--gpu-memory-utilization", "0.92", "--max-model-len", "32768"]
