apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gpt-oss-120b
  namespace: gpt-oss-inference
  labels:
    app: gpt-oss-120b
spec:
  to:
    kind: Service
    name: gpt-oss-120b
  port:
    targetPort: http
  tls:
    termination: edge
