apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vllm-modelcar
  labels:
    app: granite-4-0-h-small-car
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
