apiVersion: v1
kind: Service
metadata:
  name: granite-4-0-h-small-car
  labels:
    app: granite-4-0-h-small-car
spec:
  selector:
    app: granite-4-0-h-small-car
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  type: ClusterIP
